name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3406:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Prisma Init
        run: prisma init

      - name: Prisma Generate
        run: prisma generate

      - name: Prisma Migrate Dev
        run: prisma migrate dev --preview-feature

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
